<?php
if ( file_exists( 'config/' . $_SERVER['HTTP_HOST'] . '/config.json' ) ) {
$cache_file = 'config/' . $_SERVER['HTTP_HOST'] . '/config.json';
}else{
$cache_file = 'config/default/config.json';
}
$cache = json_decode( file_get_contents( $cache_file ), true );
return [
  'site_name' => ''.$cache['site_name'].'',
  'site_tagline' => ''.$cache['site_tagline'].'',
  'google_verify' => ''.$cache['google_verify'].'',
  'home_title' => ''.$cache['home_title'].'',
  'home_description' => ''.$cache['home_description'].'',
  'home_robots' => ''.$cache['home_robots'].'',
  'search_title' => ''.$cache['search_title'].'',
  'search_description' => ''.$cache['search_description'].'',
  'search_robots' => ''.$cache['search_robots'].'',
  'download_title' => ''.$cache['download_title'].'',
  'download_description' => ''.$cache['download_description'].'',
  'download_robots' => ''.$cache['download_robots'].'',
  'playlist_title' => ''.$cache['playlist_title'].'',
  'playlist_description' => ''.$cache['playlist_description'].'',
  'playlist_robots' => ''.$cache['playlist_robots'].'',
  'page_title' => ''.$cache['page_title'].'',
  'page_description' => ''.$cache['page_description'].'',
  'page_robots' => ''.$cache['page_robots'].'',
  'search_page_title' => ''.$cache['search_page_title'].'',
  'download_page_title' => ''.$cache['download_page_title'].'',
  'theme' => ''.$cache['theme'].'',
  'search_permalink' => ''.$cache['search_permalink'].'',
  'download_permalink' => ''.$cache['download_permalink'].'',
  'playlist_permalink' => ''.$cache['playlist_permalink'].'',
  'page_permalink' => ''.$cache['page_permalink'].'',
  'sitemap_searches_permalink' => ''.$cache['sitemap_searches_permalink'].'',
  'sitemap_keywords_permalink' => ''.$cache['sitemap_keywords_permalink'].'',
  'sitemap_index_permalink' => ''.$cache['sitemap_index_permalink'].'',
  'itunes_country' => ''.$cache['itunes_country'].'',
  'itunes_count' => $cache['itunes_count'],
  'youtube_playlist_count' => $cache['youtube_playlist_count'],
  'youtube_playlist_id' => ''.$cache['youtube_playlist_id'].'',
  'playlist_count' => $cache['playlist_count'],
  'youtube_top_videos_count' => $cache['youtube_top_videos_count'],
  'youtube_top_videos_country' => ''.$cache['youtube_top_videos_country'].'',
  'youtube_search_count' => $cache['youtube_search_count'],
  'youtube_related_count' => $cache['youtube_related_count'],
  'youtube_api_keys' => ''.$cache['youtube_api_keys'].'',
  'sitemap_limit' => $cache['sitemap_limit'],
  'use_default_store' => $cache['use_default_store'],
  'enable_cache' => $cache['enable_cache'],
  'enable_cache_download' => $cache['enable_cache_download'],
  'enable_cache_unique' => $cache['enable_cache_unique'],
  'cache_time' => $cache['cache_time'],
  'save_recent_searches' => $cache['save_recent_searches'],
  'recent_searches_limit' => $cache['recent_searches_limit'],
  'recent_searches_count' => $cache['recent_searches_count'],
  'use_default_keyword_files' => $cache['use_default_keyword_files'],
  'footer_copyright' => ''.$cache['footer_copyright'].''
];